project:
  type: website

website:
  title: "My Portfolio"
  favicon: images/space1.jpeg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Contact.qmd
        text: Contact
      - href: Appendix.qmd
        text:  Appendix 
    background: dark
  page-footer:
    center: "© 2025 Shilpi | All Rights Reserved"
  page-navigation: true


format:
  
  html:
    theme: darkly  # Optional dark theme base
    css: styles.css
    toc: true
    code-link: true
    smooth-scroll: true
    



  

